name: Buld the Docker Image

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the docker image
      run: docker build -t lemonkhan/core-cicd:1.1 .

    - name: Login to Docker-Hub
      run: echo "${{secrets.DOCKER_HUB_PASSWD}}" | docker login -u ${{secrets.DOCKER_HUB_USER}} --password-stdin

    - name: Pushing image to docker-hub
      run: docker push lemonkhan/core-cicd:1.1

    

